# configuation of jobs to run
# this is a TOML document. Boom.
title = "Jobstep config"

[jobsteps]
    [jobsteps.alpha]
    nickname = "stepUno"
    shell = "/bin/sh"
    command = "/Users/mac/craft/innov/goBatch/shell1.sh"
    args = []

    [jobsteps.beta]
    nickname = "stepDos"
    shell = "/bin/sh"
    command = "/Users/mac/craft/innov/goBatch/shell2.sh"
    args = []

    [jobsteps.gamma]
    nickname = "stepTres"
    shell = "/bin/sh"
    command = "/Users/mac/craft/innov/goBatch/shell2.sh"
    args = ["--version"]
